### ISSUE TITLE
Vulkan GPU support

### ISSUE THREAD

**Issue by amitbar05** [shader-slang/slang-torch#8]
As I understand from the documents, this package only works with CUDA.
The question is, when can we expect other GPUs be supported such as Intel and AMD? (using slang's Vulkan backend for example).

**Comment by swoods-nv** [comment]
We currently don't have any plans to resource this. We'd like to get there eventually but can't promise any timeline.

**Comment by saipraveenb25** [comment]
To add a little more context: slang-torch is currently intended to be a lightweight wrapper that uses pytorch's plugin system to do most of the heavy-lifting (and since this plugin system is focused around CUDA, that is all we can support at the moment)

Vulkan/D3D support would need a full-fledged framework to set-up and run the pipeline, which is not currently on the roadmap for the slang-torch package.
